name: Build and Publish

on:
  push:
    branches:
      - dev 

jobs:
  build_publish_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |  
          pip install -r requirements-dev.txt
      - name: Build Package
        run: python setup.py sdist bdist_wheel
      - name: Install Twine
        run: |
          pip install twine
      - name: Publish to PyPI
        run: | 
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.QT_API_TOKEN }}

  build_publish_docs:
    # Deploy to cloudflare
    runs-on: ubuntu-latest
    needs: build_publish_package
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Document
        run: |  
          pip install -r requirements-dev.txt
          sphinx-build -b html docs build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mpqp
          directory: build 